image: mobiledevops/flutter-sdk-image:3.10.1
pipelines:
  branches:
    master:
      - step:
          name: APK Push Debug
          caches:
           - gradle
          script:
           - flutter clean
           - flutter pub get
           - flutter pub run build_runner build --delete-conflicting-outputs 
           - echo "Building APK"
           - flutter build apk
           - echo "APK build scuccessfully"
          artifacts:
           - build/app/outputs/apk/**